### PR TITLE
Created samfundetUserController, updated repository to use baserepository

### PR DESCRIPTION
**Pull request by PTB03**
- [x] check if the samfundetuserEndPoints works
   -[ ] get by id
   -[ ] findall
   -[ ] create
   -[ ] delete
   -[ ] patch

### CODE REVIEW

**Comment by PTB03** [comment]
Use of docker compose instead of docker-compose: Starting with Docker Compose v2, the syntax changes to docker compose without the hyphen.

**Review by PTB03 — COMMENTED** [review]
Fixed eslint, and added function to baseRepository so totalrecords works for all endpoint using it.

**Review by Gissebass — DISMISSED** [review]

**Review by PTB03 — COMMENTED** [review]
looks good

**Review by Gissebass — APPROVED** [review]
LGTM

**Pull request merged**
